[Interface]
PrivateKey = LLAVE_PRIVADA_GENERADA=
Address = 10.10.0.1/24
ListenPort = 65534

PostUp = iptables -t nat -A PREROUTING -p tcp --dport 1:20207 -j DNAT --to-destination 172.26.10.100
PostUp = iptables -t nat -A PREROUTING -p tcp --dport 20209:65500 -j DNAT --to-destination 172.26.10.100
PostUp = iptables -A FORWARD -p tcp -d 172.26.10.100 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE

PostDown = iptables -t nat -D PREROUTING -p tcp --dport 1:20207 -j DNAT --to-destination 172.26.10.100 2>/dev/null || true
PostDown = iptables -t nat -D PREROUTING -p tcp --dport 20209:65500 -j DNAT --to-destination 172.26.10.100 2>/dev/null || true
PostDown = iptables -D FORWARD -p tcp -d 172.26.10.100 -j ACCEPT 2>/dev/null || true
PostDown = iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE 2>/dev/null || true


[Peer]
PublicKey = LLAVE_PUBLICA_DELA_CONEXION=
PresharedKey = LLAVE_COMPARTIDA=
AllowedIPs = 10.10.0.2/32, 172.26.10.0/24
PersistentKeepalive = 15
